% Create a circularArray with monopole element.
% Generated by MATLAB(R) 25.2 and Antenna Toolbox 25.2
%Generated on:21-Feb-2026 23:11:49

%% Array Properties 

SubObject = design(monopole, 2400*1e6);
arrayObject = design(circularArray('Element', SubObject), 2400*1e6, SubObject);
arrayObject.NumElements = 4;

%% Array Analysis 
% Show for circularArray
figure;
show(arrayObject) 
% Layout for circularArray
figure;
layout(arrayObject) 
% Pattern for circularArray
plotFrequency = 2400*1e6; termination = 50;
figure;
pattern(arrayObject, plotFrequency); 
% Azimuth for circularArray
plotFrequency = 2400*1e6; azRange = 0:5:360; termination = 50;
figure;
pattern(arrayObject, plotFrequency, azRange, 0);
% Elevation for circularArray
plotFrequency = 2400*1e6; elRange = 0:5:360; termination = 50;
figure;
pattern(arrayObject, plotFrequency, 45, elRange);

