% Create a linearArray with monopole element.
% Generated by MATLAB(R) 25.2 and Antenna Toolbox 25.2
%Generated on:18-Feb-2026 16:43:06

%% Array Properties 

SubObject = design(monopole, 2400*1e6);
arrayObject = design(linearArray('Element', SubObject), 2400*1e6, SubObject);
arrayObject.NumElements = 4;
arrayObject.TiltAxis = [0, 0, 1];

%% Array Analysis 
% Show for linearArray
figure;
show(arrayObject) 
% Layout for linearArray
figure;
layout(arrayObject) 
% Azimuth for linearArray
plotFrequency = 2400*1e6; azRange = 0:1:360; termination = 50;
figure;
pattern(arrayObject, plotFrequency, azRange, 0);
% Elevation for linearArray
plotFrequency = 2400*1e6; elRange = 0:1:360; termination = 50;
figure;
pattern(arrayObject, plotFrequency, 0, elRange);

